# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: gmail.com
  nonadmin_name: NonAdmin User
  nonadmin_email: nonadmin@example.com
  nonadmin_password: changeme
  approver_name: Approver User
  approver_email: approver@example.com
  approver_password: changeme
  worker_name: Worker User
  worker_email: worker@example.com
  worker_password: changeme
  secret_key_base: 9ef9c6bd1471aac37057b806d92222ac0f018e555322f8a7d97cf67793cef7e4fd08c9d7c311dbf4ac805fb88775a7ac036df279e8c812ba473455debe4aef8b
  email_provider_host: smtp.gmail.com
test:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: gmail.com
  nonadmin_name: NonAdmin User
  nonadmin_email: nonadmin@example.com
  nonadmin_password: changeme
  approver_name: Approver User
  approver_email: approver@example.com
  approver_password: changeme
  worker_name: Worker User
  worker_email: worker@example.com
  worker_password: changeme
  domain_name: gmail.com 
  secret_key_base: 26d731eb0d7fd0081b4a02ac00149add276006735205125cf483547979fa4d42191d4a8c93896b3cc2a06d4f1c229a44ca37cf49b84bf75922857f80c82b0659
  email_provider_host: smtp.gmail.com
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>

  nonadmin_name: NonAdmin User
  nonadmin_email: nonadmin@example.com
  nonadmin_password: changeme
  approver_name: Approver User
  approver_email: approver@example.com
  approver_password: changeme
  worker_name: Worker User
  worker_email: worker@example.com
  worker_password: changeme
  email_provider_host: smtp.saic.com


  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
